In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

from sklearn import metrics

datSet = pd.read_csv("advertising.csv",sep=",",header=0)
datSet.shape
datSet.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [23]:
x = datSet[['TV', 'Radio','Newspaper']].values
y = datSet['Sales'].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42) 

min_max_scale=MinMaxScaler()

x_minMax=min_max_scale.fit_transform(x)
x_train_min_max, x_test_min_max, y_train_min_max, y_test_min_max = train_test_split(x_minMax, y, test_size=0.3, random_state=42)

regressor=LinearRegression()
regressor2=LinearRegression()

regressor.fit(x_train,y_train)
regressor2.fit(x_train_min_max,y_train_min_max)

y_pred=regressor.predict(x_test)
y_pred2=regressor.predict(x_train)

y_pred3=regressor2.predict(x_test_min_max)

In [24]:
coff2= pd.DataFrame(regressor2.coef_,columns=['Coefficient'])
coff2

   Coefficient
0    13.028329
1     9.884660
2     0.782535

In [25]:
df=pd.DataFrame({"Фактический": y_test.flatten(),"Прогнозируемый": y_pred.flatten()})
df

    Фактический  Прогнозируемый
0          16.9       16.565396
1          22.4       21.188228
2          21.4       21.551071
3           7.3       10.889238
4          24.7       22.202320
5          12.6       13.355569
6          22.3       21.196925
7           8.4        7.350285
8          11.5       13.275471
9          14.9       15.124495
10          9.5        9.014430
11          8.7        6.525428
12         11.9       14.302060
13          5.3        8.970260
14         10.3        9.456796
15         11.7       12.004544
16          5.5        8.915494
17         16.6       16.156193
18         11.3       10.295829
19         18.9       18.724736
20         19.7       19.768218
21         12.5       13.774690
22         10.9       12.496389
23         22.2       21.535018
24          9.3        7.608607
25          8.1        5.611980
26         21.7       20.917595
27         13.4       11.806277
28         10.6        9.080766
29          5.7        8.514120
30         10.6       12.176049
31         11.3        9.969194
32         23.7       21.730090
33          8.7       12.777706
34         16.1       18.101136
35         20.7       20.075908
36         11.6       14.262026
37         20.8       20.938265
38         11.9       10.839388
39          6.9        4.381906
40         11.0        9.513324
41         12.8       12.404863
42         10.1       10.170454
43          9.7        8.090814
44         11.6       13.163884
45          7.6        5.224355
46         10.5        9.288938
47         14.6       14.093307
48         10.4        8.690245
49         12.0       11.661198
50         14.6       15.718484
51         11.7       11.631569
52          7.2       13.353607
53          6.6       11.153147
54          9.4        6.336368
55         11.0        9.761580
56         10.9        9.419571
57         25.4       24.255165
58          7.6        7.695191
59         11.7       12.153176

In [26]:
df=pd.DataFrame({"Фактический": y_train.flatten(),"Прогнозируемый": y_pred2.flatten()})
df

     Фактический  Прогнозируемый
0           15.0       17.391498
1           15.5       15.191962
2           11.9       11.416507
3            9.2       11.206105
4           12.8       16.392562
..           ...             ...
135          7.2        6.207002
136         19.0       18.574600
137         19.4       19.382850
138         12.6       12.119172
139         14.8       17.214448

[140 rows x 2 columns]

In [27]:
print("Среднекватратичное отклонение тестовые ",metrics.mean_squared_error(y_test,y_pred))

print("Среднекватратичное отклонение тренировочное ",metrics.mean_squared_error(y_train,y_pred2))

print("Среднекватратичное отклонение тренировочное для максимизируемого ",metrics.mean_squared_error(y_test,y_pred3))

Среднекватратичное отклонение тестовые  3.7967972367152227
Среднекватратичное отклонение тренировочное  2.4793551789057866
Среднекватратичное отклонение тренировочное для максимизируемого  3.7967972367152196